name: build

permissions:
  contents: write

on:
  push:
    tags:
      - "v*"
    branches:
      - "main"
  pull_request:

defaults:
  run:
    shell: bash --noprofile --norc -CeEuo pipefail {0}

jobs:
  release:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "oracle"
          java-version: "25"
      - name: test
        run: |
          bash ./rhino.sh test.js
      - name: build`
        run: |
          which java
          which jpackage
          java --version
          jpackage --version
          echo $JAVA_HOME

          bash ./build.sh

      - name: release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "rhino.sh,rhino-all-1.8.0.jar"
          allowUpdates: true
          tag: "nightly"
          name: "nightly"
          token: ${{ secrets.GITHUB_TOKEN }}
          commit: main
          replacesArtifacts: true